version: "3.3"

services:
  jobs:
    container_name: jobs_api
    image: jobs_api
    build:
      context: ./services/jobs
      dockerfile: Dockerfile
      #target: development
    command: npm run start:debug
    ports:
        - 3000:3000
    depends_on: [searches]
    networks:
      - be

  searches:
    container_name: searches_consumer
    image: searches_consumer
    build:
      context: ./services/searches
      dockerfile: Dockerfile
      #target: development
    command: npm run start:debug
    depends_on: [db]
    networks:
      - be

  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - 3306:3306
    networks:
      - be

networks:
  be:

volumes:
  mysql_data:
