version: '3'

services:
  searches:
    container_name: searches_consumer_standalone
    build:
      context: .
      dockerfile: Dockerfile
    command: node dist/main
    environment:
      DB_HOST: searches_db
      REDIS_HOST: 
    networks:
      - be

  searches_db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - 3306:3306
    networks:
      - be

networks:
  be:

volumes:
  mysql_data: